version: "3.8"

volumes:
  rabbitmq_data:

services:  

  ###############################################
  # Place Order: The master microservice
  ###############################################
  master:
    build:
      context: ./master
      dockerfile: master.Dockerfile
    image: ryan2409/master:esd
    restart: always
    depends_on:
      - user
      - rental
      - payment
      - error
      - email
      - rabbitmq
    environment:
      rabbit_host: rabbitmq
      rabbit_port: 5672
      user_URL: http://user:<PORTNO>/user
      rental_URL: http://rental:<PORTNO>/rental 
      payment_URL: http://payment:<PORTNO>/payment
      PYTHONUNBUFFERED: 1
    ports:
      - "5100:5100"