version: "3.8"

volumes:
  rabbitmq_data:

services:  

  ###############################################
  # Master: The master microservice
  ###############################################
  master:
    build:
      context: ./master
      dockerfile: Dockerfile
    image: ryan2409/master:esd
    restart: always
    # depends_on:
      # - user
      # - rental
      # - payment
      # - error
      # - email
      # - rabbitmq
    environment:
      rabbit_host: rabbitmq
      rabbit_port: 5672
      # rental_get_URL: http://rental:5002/rental/info 
      # rental_update_URL: http://rental:5002/rental/update 
      # payment_submit_URL: http://payment:5004/payment/rent
      # payment_release_URL: http://payment:5004/payment/return
      PYTHONUNBUFFERED: 1
    ports:
      - "5100:5100"