version: "3.8"

volumes:
  rabbitmq_data:

services:  

  ###############################################
  # Master: The master microservice
  ###############################################
  master:
    build:
      context: ./master
      dockerfile: master.Dockerfile
    image: ryan2409/master:esd
    restart: always
    # depends_on:
      # - user
      # - rental
      # - payment
      # - error
      # - email
      # - rabbitmq
    environment:
      rabbit_host: rabbitmq
      rabbit_port: 5672
      # rental_get_URL: http://rental:<PORTNO>/rental 
      # rental_create_URL: http://rental:<PORTNO>/rental/create 
      # rental_update_URL: http://rental:<PORTNO>/rental/update 
      # payment_submit_URL: http://payment:4242/payment/rent
      # payment_release_URL: http://payment:4242/payment/return
      PYTHONUNBUFFERED: 1
    ports:
      - "5100:5100"