version: "3.8"

volumes:
  rabbitmq_data:

services:  
  ###############################################
  # user: The user microservice
  ###############################################
  user:
    build:
      context: ./user
      dockerfile: Dockerfile
    image: ryan2409/user:esd
    restart: always
    environment:
      dbURL: mysql+mysqlconnector://is213@host.docker.internal:3306/user
      PYTHONUNBUFFERED: 1
  ###############################################
  # rental: The rental microservice
  ###############################################
  rental:
    build:
      context: ./rental
      dockerfile: Dockerfile
    image: ryan2409/rental:esd
    restart: always
    environment:
      dbURL: mysql+mysqlconnector://is213@host.docker.internal:3306/rental
      PYTHONUNBUFFERED: 1
  ###############################################
  # rabbitMQ: The amqp
  ###############################################
  rabbitmq:
    image: rabbitmq:3-management
    hostname: esd-rabbit
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes: 
      - ./rabbitmq.config:/etc/rabbitmq/rabbitmq.config
      - ./rabbitmq_definitions.json:/etc/rabbitmq/rabbitmq_definitions.json
      - rabbitmq_data:/var/lib/rabbitmq
  
  ###############################################
  # error: The error microservice
  ###############################################
  error:
    build:
      context: ./error
      dockerfile: Dockerfile
    image: ryan2409/error:esd
    restart: always
    depends_on:
      - rabbitmq
    environment:
      rabbit_host: rabbitmq
      rabbit_port: 5672
      e_queue_name: Error
      PYTHONUNBUFFERED: 1
      dbURL: mysql+mysqlconnector://is213@host.docker.internal:3306/error
  
  ###############################################
  # Master: The master microservice
  ###############################################
  master:
    build:
      context: ./master
      dockerfile: Dockerfile
    image: ryan2409/master:esd
    restart: always
    depends_on:
      - user
      - rental
      # - payment
      - error
      # - email
      - rabbitmq
    environment:
      rabbit_host: rabbitmq
      rabbit_port: 5672
      rental_get_URL: http://rental:5002/rental/info 
      rental_update_URL: http://rental:5002/rental/update 
      # payment_submit_URL: http://payment:5004/payment/rent
      # payment_release_URL: http://payment:5004/payment/return
      PYTHONUNBUFFERED: 1
    ports:
      - "5100:5100"