apiVersion: apps/v1
kind: Deployment
metadata:
  name: master-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: master
  template:
    metadata:
      labels:
        app: master
    spec:
      containers:
        - name: master
          image: brandonlim99/kubernetes_test:master_amqp.v1
          ports:
            - containerPort: 5100
          env:
            - name: user_URL
              value: "http://user-service:5001/user"
            - name: rental_update_URL
              value: "http://rental-service:5002/rental/update"
            - name: rental_get_URL
              value: "http://rental-service:5002/rental/info"
            - name: email_URL
              value: "http://email-service:5003/email"
            - name: payment_submit_URL
              value: "http://payment-service:5004/payment/rent"
            - name: payment_release_URL
              value: "http://payment-service:5004/payment/return"
            - name: hostname
              value: "rabbitmq-service"
            - name: exchangename
              value: "drivewhere_topic"
