version: "3.8"

volumes:
  rabbitmq_data:

services:  
  ###############################################
  # user: The user microservice
  ###############################################
  user:
    build:
      context: ./user
      dockerfile: Dockerfile
    image: ryan2409/user:esd
    restart: always
    environment:
      dbURL: ${USER_dbURL}
      PORT: ${USER_PORT}
      PYTHONUNBUFFERED: 1
  ###############################################
  # rental: The rental microservice
  ###############################################
  rental:
    build:
      context: ./rental
      dockerfile: Dockerfile
    image: ryan2409/rental:esd
    restart: always
    environment:
      dbURL: ${RENTAL_dbURL}
      PORT: ${RENTAL_PORT}
      GMAPS_KEY: ${GMAPS_KEY}
      PYTHONUNBUFFERED: 1
    ports:
      - "${RENTAL_PORT}:${RENTAL_PORT}"
  ###############################################
  # payment: The payment microservice
  ###############################################
  payment:
    build:
      context: ./payment
      dockerfile: Dockerfile
    image: ryan2409/payment:esd
    restart: always
    environment:
      dbURL: ${PAYMENT_dbURL}
      HOST: ${PAYMENT_HOST}
      PORT: ${PAYMENT_PORT}
      MASTER_HOST: ${MASTER_HOST}
      MASTER_PORT: ${MASTER_PORT}
      STRIPE_KEY: ${STRIPE_KEY}
      PYTHONUNBUFFERED: 1
  ###############################################
  # rabbitMQ: The amqp
  ###############################################
  rabbitmq:
    image: rabbitmq:3-management
    hostname: esd-rabbit
    restart: always
    ports:
      - "${RABBIT_PORT}:${RABBIT_PORT}"
      - "${RABBIT_WEB_PORT}:${RABBIT_WEB_PORT}"
    volumes: 
      - ./rabbitmq.config:/etc/rabbitmq/rabbitmq.config
      - ./rabbitmq_definitions.json:/etc/rabbitmq/rabbitmq_definitions.json
      - rabbitmq_data:/var/lib/rabbitmq
  
  ###############################################
  # error: The error microservice
  ###############################################
  error:
    build:
      context: ./error
      dockerfile: Dockerfile
    image: ryan2409/error:esd
    restart: always
    depends_on:
      - rabbitmq
    environment:
      rabbit_host: ${RABBIT_HOST}
      rabbit_port: ${RABBIT_PORT}
      e_queue_name: ${ERROR_QUEUE}
      PYTHONUNBUFFERED: 1
      dbURL: ${ERROR_dbURL}
      PORT: ${ERROR_PORT}
  
  ###############################################
  # email: The email microservice
  ###############################################
  email:
    build:
      context: ./email
      dockerfile: Dockerfile
    image: ryan2409/email:esd
    restart: always
    depends_on:
      - rabbitmq
    environment:
      rabbit_host: ${RABBIT_HOST}
      rabbit_port: ${RABBIT_PORT}
      a_queue_name: ${EMAIL_QUEUE}
      GMAIL_APP_PASS: ${GMAIL_APP_PASS}
      PYTHONUNBUFFERED: 1
  
  ###############################################
  # Master: The master microservice
  ###############################################
  master:
    build:
      context: ./master
      dockerfile: Dockerfile
    image: ryan2409/master:esd
    restart: always
    depends_on:
      - user
      - rental
      - payment
      - error
      - email
      - rabbitmq
    environment:
      rabbit_host: ${RABBIT_HOST}
      rabbit_port: ${RABBIT_PORT}
      rental_get_URL: http://${RENTAL_HOST}:${RENTAL_PORT}/rental/info 
      rental_update_URL: http://${RENTAL_HOST}:${RENTAL_PORT}/rental/update
      rental_list_URL: http://${RENTAL_HOST}:${RENTAL_PORT}/rental
      user_get_URL: http://${USER_HOST}:${USER_PORT}/user
      payment_submit_URL: http://${PAYMENT_HOST}:${PAYMENT_PORT}/payment/rent
      payment_release_URL: http://${PAYMENT_HOST}:${PAYMENT_PORT}/payment/return
      PORT: ${MASTER_PORT}
      FRONTEND_HOST: ${FRONTEND_HOST}
      PAYMENT_HOST: ${PAYMENT_HOST}
      PAYMENT_PORT: ${PAYMENT_PORT}
      PYTHONUNBUFFERED: 1
    ports:
      - "${MASTER_PORT}:${MASTER_PORT}"
