apiVersion: apps/v1
kind: Deployment
metadata:
  name: error-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: error
  template:
    metadata:
      labels:
        app: error
    spec:
      containers:
        - name: error
          image: brandonlim99/kubernetes_test:error
          ports:
            - containerPort: 5005
          env:
            - name: dbURL
              value: "mysql+mysqlconnector://root:1234@db-service:3306/drivewhereDB"
            - name: rabbit_host
              value : "rabbitmq-service"
            - name: rabbit_port
              value: "5672"
            - name: e_queue_name
              value: "Error"

--- 
apiVersion: v1
kind: Service
metadata:
  name: error-service
spec:
  selector:
    app: error
  ports:
    - protocol: TCP
      port: 5005
      targetPort: 5005