apiVersion: apps/v1
kind: Deployment
metadata:
  name: rental-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rental
  template:
    metadata:
      labels:
        app: rental
    spec:
      containers:
        - name: rental
          image: brandonlim99/drivewhereimg:rental
          ports:
            - containerPort: 5002
          env:
            - name: dbURL
              value: "mysql+mysqlconnector://root:1234@db-service:3306/drivewhereDB"
            - name: GMAPS_KEY
              valueFrom:
                secretKeyRef:
                  name: gmaps-key
                  key: APIKEY

---
apiVersion: v1
kind: Service
metadata:
  name: rental-service
spec:
  selector:
    app: rental
  ports:
    - protocol: TCP
      port: 5002
      targetPort: 5002
