apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
        - name: user
          image: brandonlim99/drivewhereimg:user
          ports:
            - containerPort: 5001
          env: 
          - name: dbURL
            value: "mysql+mysqlconnector://root:1234@db-service:3306/drivewhereDB"

---
apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  selector:
    app: user
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001
